syntax = "proto3";

option java_package = "plant.grpc";

package plantcomms;

service PlantCommunication {
    rpc SendGreetingsMessage(GreetingsMessage) returns (GreetingsResponse);

    rpc SendElectionMessage(ElectionMessage) returns (ElectionResponse);

    // rpc SendWinnerMessage(WinnerMessage) returns (WinnerResponse);
}

message GreetingsMessage {
    string plant_id = 1;
    string listening_address = 2;
}

message GreetingsResponse {
    bool success = 1;
    string message = 2;
}

message ElectionMessage {
    string initiator_id = 1;
    string current_holder_id = 2;
    double best_bid = 3;
    string current_winner_id = 4;
    string request_id = 5;
    int32 energy_request = 6;
}

message ElectionResponse {
    bool success = 1;
    string message = 2;   
}

// message WinnerMessage {
//     string winner_id = 1;
//     string request_id = 2;
// }
// 
// message WinnerResponse {
//     bool success = 1;
//     string message = 2;
// }